"""
Strategy module — All options trading strategies in one file.
Iron Condor, Straddle/Strangle, Vertical Spreads, Calendar Spread,
Naked Options, and the AI-driven strategy selector.
"""

import logging
from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from datetime import datetime
from typing import Optional

import config

logger = logging.getLogger(__name__)


@dataclass
class StrategyLeg:
    """Single leg of a multi-leg options strategy."""
    option_type: str = "CE"  # CE or PE
    strike: float = 0
    side: str = "BUY"  # BUY or SELL
    qty: int = 1
    premium: float = 0
    delta: float = 0
    theta: float = 0


@dataclass
class StrategyOrder:
    """Order generated by a strategy."""
    strategy_name: str = ""
    symbol: str = ""
    legs: list[StrategyLeg] = field(default_factory=list)
    max_profit: float = 0
    max_loss: float = 0
    breakeven: list[float] = field(default_factory=list)
    net_premium: float = 0  # +ve = credit, -ve = debit
    margin_required: float = 0
    confidence: float = 0
    signal_score: float = 0
    entry_reason: str = ""
    stoploss_pct: float = 15   # Tight 15% default — cut losses fast


class BaseStrategy(ABC):
    """Abstract base for all strategies."""

    name: str = "BASE"

    @abstractmethod
    def evaluate(self, signal, chain_df, underlying_price, **kwargs) -> Optional[StrategyOrder]:
        """Evaluate whether to enter this strategy. Returns order or None."""
        pass

    def _find_atm(self, chain_df, price):
        return float(min(chain_df["strike"].unique(), key=lambda s: abs(s - price)))

    def _get_strike_row(self, chain_df, strike):
        rows = chain_df[chain_df["strike"] == strike]
        if not rows.empty:
            return rows.iloc[0]
        # Find nearest available strike
        nearest = float(min(chain_df["strike"].unique(), key=lambda s: abs(s - strike)))
        return chain_df[chain_df["strike"] == nearest].iloc[0]

    def _safe_premium(self, chain_df, strike, col):
        """Get premium for a strike, finding nearest if exact strike missing. Never returns 0."""
        row = chain_df[chain_df["strike"] == strike]
        if not row.empty:
            p = float(row.iloc[0][col])
            return max(p, config.MIN_OPTION_PREMIUM)
        # Find nearest available strike
        strikes = chain_df["strike"].unique()
        nearest = float(min(strikes, key=lambda s: abs(s - strike)))
        row = chain_df[chain_df["strike"] == nearest]
        if not row.empty:
            p = float(row.iloc[0][col])
            return max(p, config.MIN_OPTION_PREMIUM)
        return config.MIN_OPTION_PREMIUM


class IronCondorStrategy(BaseStrategy):
    """Iron Condor — profit in sideways markets."""
    name = "IRON_CONDOR"

    def evaluate(self, signal, chain_df, price, **kw) -> Optional[StrategyOrder]:
        if chain_df.empty or signal.regime not in ("SIDEWAYS", "LOW_VOLATILITY"):
            return None

        strikes = sorted(chain_df["strike"].unique())
        atm = self._find_atm(chain_df, price)
        si = kw.get("strike_interval", 50)

        sell_ce = atm + si * 4   # 200pts OTM — room for intraday moves
        buy_ce = atm + si * 5
        sell_pe = atm - si * 4   # 200pts OTM
        buy_pe = atm - si * 5

        # Get premiums — safe lookup never returns 0
        sell_ce_p = self._safe_premium(chain_df, sell_ce, "ce_ltp")
        buy_ce_p = self._safe_premium(chain_df, buy_ce, "ce_ltp")
        sell_pe_p = self._safe_premium(chain_df, sell_pe, "pe_ltp")
        buy_pe_p = self._safe_premium(chain_df, buy_pe, "pe_ltp")

        # Validate: sell premium must be > buy premium for a credit spread
        net = (sell_ce_p + sell_pe_p) - (buy_ce_p + buy_pe_p)
        if net <= 0:
            return None  # Not a viable iron condor

        lot = kw.get("lot_size", 25)

        # Validate all legs have minimum premium
        for p in [sell_ce_p, buy_ce_p, sell_pe_p, buy_pe_p]:
            if p < config.MIN_PREMIUM_TO_TRADE:
                return None

        return StrategyOrder(
            strategy_name=self.name, symbol=kw.get("symbol", "NIFTY"),
            legs=[
                StrategyLeg("CE", sell_ce, "SELL", 1, sell_ce_p),
                StrategyLeg("CE", buy_ce, "BUY", 1, buy_ce_p),
                StrategyLeg("PE", sell_pe, "SELL", 1, sell_pe_p),
                StrategyLeg("PE", buy_pe, "BUY", 1, buy_pe_p),
            ],
            max_profit=net * lot,
            max_loss=(si - net) * lot,
            breakeven=[sell_pe - net, sell_ce + net],
            net_premium=net,
            confidence=signal.confidence,
            signal_score=signal.score,
            entry_reason=f"Sideways regime | Score: {signal.score}",
            stoploss_pct=25,  # Credit strategy: wider stop
        )


class StraddleStrangleStrategy(BaseStrategy):
    """Straddle/Strangle — volatility plays."""
    name = "STRADDLE_STRANGLE"

    def evaluate(self, signal, chain_df, price, **kw) -> Optional[StrategyOrder]:
        if chain_df.empty:
            return None

        atm = self._find_atm(chain_df, price)
        si = kw.get("strike_interval", 50)
        lot = kw.get("lot_size", 25)
        regime = signal.regime

        if regime == "HIGH_VOLATILITY":
            # Long straddle
            ce_p = self._safe_premium(chain_df, atm, "ce_ltp")
            pe_p = self._safe_premium(chain_df, atm, "pe_ltp")

            if ce_p < config.MIN_PREMIUM_TO_TRADE or pe_p < config.MIN_PREMIUM_TO_TRADE:
                return None

            cost = ce_p + pe_p

            return StrategyOrder(
                strategy_name="LONG_STRADDLE", symbol=kw.get("symbol", "NIFTY"),
                legs=[
                    StrategyLeg("CE", atm, "BUY", 1, ce_p),
                    StrategyLeg("PE", atm, "BUY", 1, pe_p),
                ],
                max_profit=float("inf"),
                max_loss=cost * lot,
                breakeven=[atm - cost, atm + cost],
                net_premium=-cost,
                confidence=signal.confidence,
                signal_score=signal.score,
                entry_reason=f"High volatility regime | Long Straddle",
            )
        elif regime in ("SIDEWAYS", "LOW_VOLATILITY"):
            # Short strangle
            sell_ce = atm + si * 2
            sell_pe = atm - si * 2
            ce_p = self._safe_premium(chain_df, sell_ce, "ce_ltp")
            pe_p = self._safe_premium(chain_df, sell_pe, "pe_ltp")

            if ce_p < config.MIN_PREMIUM_TO_TRADE or pe_p < config.MIN_PREMIUM_TO_TRADE:
                return None

            net = ce_p + pe_p

            return StrategyOrder(
                strategy_name="SHORT_STRANGLE", symbol=kw.get("symbol", "NIFTY"),
                legs=[
                    StrategyLeg("CE", sell_ce, "SELL", 1, ce_p),
                    StrategyLeg("PE", sell_pe, "SELL", 1, pe_p),
                ],
                max_profit=net * lot,
                max_loss=float("inf"),
                breakeven=[sell_pe - net, sell_ce + net],
                net_premium=net,
                confidence=signal.confidence,
                signal_score=signal.score,
                entry_reason=f"Low vol regime | Short Strangle",
            )
        return None


class VerticalSpreadStrategy(BaseStrategy):
    """Bull/Bear Call/Put Spreads — directional with limited risk."""
    name = "VERTICAL_SPREAD"

    def evaluate(self, signal, chain_df, price, **kw) -> Optional[StrategyOrder]:
        if chain_df.empty or signal.direction == "NEUTRAL":
            return None

        atm = self._find_atm(chain_df, price)
        si = kw.get("strike_interval", 50)
        lot = kw.get("lot_size", 25)

        if signal.direction in ("STRONG_BUY", "BUY"):
            # Bull Call Spread
            buy_s = atm
            sell_s = atm + si * 3   # Wider spread — more profit potential
            buy_p = self._safe_premium(chain_df, buy_s, "ce_ltp")
            sell_p = self._safe_premium(chain_df, sell_s, "ce_ltp")
            debit = buy_p - sell_p

            if debit <= 0 or buy_p < config.MIN_PREMIUM_TO_TRADE:
                return None

            return StrategyOrder(
                strategy_name="BULL_CALL_SPREAD", symbol=kw.get("symbol", "NIFTY"),
                legs=[
                    StrategyLeg("CE", buy_s, "BUY", 1, buy_p),
                    StrategyLeg("CE", sell_s, "SELL", 1, sell_p),
                ],
                max_profit=(sell_s - buy_s - debit) * lot,
                max_loss=debit * lot,
                breakeven=[buy_s + debit],
                net_premium=-debit,
                confidence=signal.confidence,
                signal_score=signal.score,
                entry_reason=f"Bullish | {signal.direction}",
            )
        else:
            # Bear Put Spread
            buy_s = atm
            sell_s = atm - si * 3   # Wider spread — more profit potential
            buy_p = self._safe_premium(chain_df, buy_s, "pe_ltp")
            sell_p = self._safe_premium(chain_df, sell_s, "pe_ltp")
            debit = buy_p - sell_p

            if debit <= 0 or buy_p < config.MIN_PREMIUM_TO_TRADE:
                return None

            return StrategyOrder(
                strategy_name="BEAR_PUT_SPREAD", symbol=kw.get("symbol", "NIFTY"),
                legs=[
                    StrategyLeg("PE", buy_s, "BUY", 1, buy_p),
                    StrategyLeg("PE", sell_s, "SELL", 1, sell_p),
                ],
                max_profit=(buy_s - sell_s - debit) * lot,
                max_loss=debit * lot,
                breakeven=[buy_s - debit],
                net_premium=-debit,
                confidence=signal.confidence,
                signal_score=signal.score,
                entry_reason=f"Bearish | {signal.direction}",
            )


class NakedOptionStrategy(BaseStrategy):
    """Naked CE/PE — high conviction directional trades only."""
    name = "NAKED_OPTION"

    def evaluate(self, signal, chain_df, price, **kw) -> Optional[StrategyOrder]:
        if chain_df.empty or signal.direction not in ("STRONG_BUY", "STRONG_SELL"):
            return None

        atm = self._find_atm(chain_df, price)
        si = kw.get("strike_interval", 50)
        lot = kw.get("lot_size", 25)

        if signal.direction == "STRONG_BUY":
            strike = atm + si  # Slightly OTM CE
            premium = self._safe_premium(chain_df, strike, "ce_ltp")

            if premium < config.MIN_PREMIUM_TO_TRADE:
                return None

            return StrategyOrder(
                strategy_name="NAKED_CE", symbol=kw.get("symbol", "NIFTY"),
                legs=[StrategyLeg("CE", strike, "BUY", 1, premium)],
                max_profit=float("inf"),
                max_loss=premium * lot,
                breakeven=[strike + premium],
                net_premium=-premium,
                confidence=signal.confidence,
                signal_score=signal.score,
                entry_reason=f"Strong bullish | Naked CE",
                stoploss_pct=20,  # Naked options: moderate stop
            )
        else:
            strike = atm - si
            premium = self._safe_premium(chain_df, strike, "pe_ltp")

            if premium < config.MIN_PREMIUM_TO_TRADE:
                return None

            return StrategyOrder(
                strategy_name="NAKED_PE", symbol=kw.get("symbol", "NIFTY"),
                legs=[StrategyLeg("PE", strike, "BUY", 1, premium)],
                max_profit=float("inf"),
                max_loss=premium * lot,
                breakeven=[strike - premium],
                net_premium=-premium,
                confidence=signal.confidence,
                signal_score=signal.score,
                entry_reason=f"Strong bearish | Naked PE",
                stoploss_pct=20,  # Naked options: moderate stop
            )


class StrategySelector:
    """AI-driven strategy selector based on market regime + signal."""

    def __init__(self):
        self.strategies = {
            "IRON_CONDOR": IronCondorStrategy(),
            "STRADDLE_STRANGLE": StraddleStrangleStrategy(),
            "VERTICAL_SPREAD": VerticalSpreadStrategy(),
            "NAKED_OPTION": NakedOptionStrategy(),
        }

    def select_and_evaluate(self, signal, chain_df, price, **kw) -> Optional[StrategyOrder]:
        """Select the best strategy for current conditions and evaluate."""
        suggested = signal.suggested_strategy
        regime = signal.regime
        direction = signal.direction

        # Priority order based on regime
        if regime in ("SIDEWAYS", "LOW_VOLATILITY"):
            order_of_pref = ["IRON_CONDOR", "STRADDLE_STRANGLE"]
        elif regime == "HIGH_VOLATILITY":
            order_of_pref = ["STRADDLE_STRANGLE", "VERTICAL_SPREAD"]
        elif direction in ("STRONG_BUY", "STRONG_SELL"):
            order_of_pref = ["NAKED_OPTION", "VERTICAL_SPREAD"]
        else:
            order_of_pref = ["VERTICAL_SPREAD", "IRON_CONDOR"]

        for strat_name in order_of_pref:
            strat = self.strategies.get(strat_name)
            if strat:
                order = strat.evaluate(signal, chain_df, price, **kw)
                if order:
                    logger.info("Strategy selected: %s", order.strategy_name)
                    return order

        return None
