"""
Database ORM models — tracks EVERYTHING.
"Data is King" — every signal, trade, tick, sentiment score is persisted.
"""

from datetime import datetime
from sqlalchemy import (
    Column, Integer, Float, String, DateTime, Boolean, Text, JSON,
    BigInteger, Enum as SQLEnum, Index,
)
from database.connection import Base
import enum


# ═══════════════════════════════════════════════════════════
#  ENUMS
# ═══════════════════════════════════════════════════════════

class OrderSide(str, enum.Enum):
    BUY = "BUY"
    SELL = "SELL"


class OrderType(str, enum.Enum):
    MARKET = "MARKET"
    LIMIT = "LIMIT"


class OptionType(str, enum.Enum):
    CE = "CE"
    PE = "PE"


class TradeStatus(str, enum.Enum):
    OPEN = "OPEN"
    CLOSED = "CLOSED"
    CANCELLED = "CANCELLED"
    EXPIRED = "EXPIRED"


class SignalDirection(str, enum.Enum):
    STRONG_BUY = "STRONG_BUY"
    BUY = "BUY"
    NEUTRAL = "NEUTRAL"
    SELL = "SELL"
    STRONG_SELL = "STRONG_SELL"


class MarketRegime(str, enum.Enum):
    TRENDING_UP = "TRENDING_UP"
    TRENDING_DOWN = "TRENDING_DOWN"
    SIDEWAYS = "SIDEWAYS"
    HIGH_VOLATILITY = "HIGH_VOLATILITY"
    LOW_VOLATILITY = "LOW_VOLATILITY"


class StrategyName(str, enum.Enum):
    IRON_CONDOR = "IRON_CONDOR"
    SHORT_STRADDLE = "SHORT_STRADDLE"
    SHORT_STRANGLE = "SHORT_STRANGLE"
    LONG_STRADDLE = "LONG_STRADDLE"
    LONG_STRANGLE = "LONG_STRANGLE"
    BULL_CALL_SPREAD = "BULL_CALL_SPREAD"
    BULL_PUT_SPREAD = "BULL_PUT_SPREAD"
    BEAR_CALL_SPREAD = "BEAR_CALL_SPREAD"
    BEAR_PUT_SPREAD = "BEAR_PUT_SPREAD"
    CALENDAR_SPREAD = "CALENDAR_SPREAD"
    NAKED_CE = "NAKED_CE"
    NAKED_PE = "NAKED_PE"


# ═══════════════════════════════════════════════════════════
#  TRADE LOG — Every single trade ever taken
# ═══════════════════════════════════════════════════════════

class Trade(Base):
    __tablename__ = "trades"

    id = Column(Integer, primary_key=True, autoincrement=True)
    created_at = Column(DateTime, default=datetime.utcnow, index=True)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)

    # Instrument details
    symbol = Column(String(50), nullable=False, index=True)
    exchange_segment = Column(String(20), nullable=False)
    security_id = Column(String(30))
    option_type = Column(SQLEnum(OptionType))
    strike_price = Column(Float)
    expiry_date = Column(String(20))

    # Order details
    side = Column(SQLEnum(OrderSide), nullable=False)
    order_type = Column(SQLEnum(OrderType), default=OrderType.MARKET)
    quantity = Column(Integer, nullable=False)
    lot_size = Column(Integer)

    # Prices
    entry_price = Column(Float, nullable=False)
    exit_price = Column(Float)
    stoploss_price = Column(Float)
    target_price = Column(Float)

    # P&L
    brokerage = Column(Float, default=0)
    slippage = Column(Float, default=0)
    gross_pnl = Column(Float, default=0)
    net_pnl = Column(Float, default=0)

    # Status
    status = Column(SQLEnum(TradeStatus), default=TradeStatus.OPEN, index=True)
    exit_reason = Column(String(100))

    # Strategy info
    strategy = Column(SQLEnum(StrategyName))
    strategy_params = Column(JSON)

    # Signal info at entry
    entry_signal_score = Column(Float)
    entry_signal_direction = Column(SQLEnum(SignalDirection))
    entry_signals_detail = Column(JSON)

    # Greeks at entry
    entry_delta = Column(Float)
    entry_gamma = Column(Float)
    entry_theta = Column(Float)
    entry_vega = Column(Float)
    entry_iv = Column(Float)

    # Greeks at exit
    exit_delta = Column(Float)
    exit_gamma = Column(Float)
    exit_theta = Column(Float)
    exit_vega = Column(Float)
    exit_iv = Column(Float)

    # Market context
    underlying_price_at_entry = Column(Float)
    underlying_price_at_exit = Column(Float)
    vix_at_entry = Column(Float)
    vix_at_exit = Column(Float)
    pcr_at_entry = Column(Float)
    sentiment_score_at_entry = Column(Float)
    market_regime_at_entry = Column(SQLEnum(MarketRegime))

    # Timestamps
    entry_time = Column(DateTime, index=True)
    exit_time = Column(DateTime)

    __table_args__ = (
        Index("ix_trades_symbol_status", "symbol", "status"),
        Index("ix_trades_strategy_created", "strategy", "created_at"),
    )


# ═══════════════════════════════════════════════════════════
#  SIGNAL LOG — Every signal generated by the system
# ═══════════════════════════════════════════════════════════

class Signal(Base):
    __tablename__ = "signals"

    id = Column(Integer, primary_key=True, autoincrement=True)
    created_at = Column(DateTime, default=datetime.utcnow, index=True)

    symbol = Column(String(50), nullable=False, index=True)
    direction = Column(SQLEnum(SignalDirection), nullable=False)
    score = Column(Float, nullable=False)

    # Breakdown
    technical_score = Column(Float)
    greeks_score = Column(Float)
    oi_score = Column(Float)
    sentiment_score = Column(Float)
    regime_score = Column(Float)

    # Details
    technical_detail = Column(JSON)
    greeks_detail = Column(JSON)
    oi_detail = Column(JSON)
    sentiment_detail = Column(JSON)
    regime = Column(SQLEnum(MarketRegime))

    # Was this signal acted upon?
    acted_upon = Column(Boolean, default=False)
    trade_id = Column(Integer)

    underlying_price = Column(Float)
    vix = Column(Float)


# ═══════════════════════════════════════════════════════════
#  OPTION CHAIN SNAPSHOT — Track OI changes over time
# ═══════════════════════════════════════════════════════════

class OptionChainSnapshot(Base):
    __tablename__ = "option_chain_snapshots"

    id = Column(BigInteger, primary_key=True, autoincrement=True)
    captured_at = Column(DateTime, default=datetime.utcnow, index=True)

    symbol = Column(String(50), nullable=False, index=True)
    expiry_date = Column(String(20), nullable=False)
    strike_price = Column(Float, nullable=False)
    option_type = Column(SQLEnum(OptionType), nullable=False)

    # OI data
    open_interest = Column(BigInteger)
    change_in_oi = Column(BigInteger)
    oi_pct_change = Column(Float)

    # Price data
    ltp = Column(Float)
    change_pct = Column(Float)
    volume = Column(BigInteger)
    bid_price = Column(Float)
    ask_price = Column(Float)
    bid_qty = Column(Integer)
    ask_qty = Column(Integer)

    # Greeks
    iv = Column(Float)
    delta = Column(Float)
    gamma = Column(Float)
    theta = Column(Float)
    vega = Column(Float)

    __table_args__ = (
        Index("ix_oc_symbol_expiry_strike", "symbol", "expiry_date", "strike_price"),
        Index("ix_oc_captured", "captured_at"),
    )


# ═══════════════════════════════════════════════════════════
#  OI ANALYSIS LOG — Tracks OI-based signals
# ═══════════════════════════════════════════════════════════

class OIAnalysis(Base):
    __tablename__ = "oi_analysis"

    id = Column(Integer, primary_key=True, autoincrement=True)
    captured_at = Column(DateTime, default=datetime.utcnow, index=True)

    symbol = Column(String(50), nullable=False, index=True)
    expiry_date = Column(String(20))
    strike_price = Column(Float)

    # NSE OCA-style data
    call_sum = Column(Float)
    put_sum = Column(Float)
    difference = Column(Float)
    call_boundary = Column(Float)
    put_boundary = Column(Float)
    pcr = Column(Float)

    # Signals
    oi_trend = Column(String(20))       # "BULLISH", "BEARISH", "SIDEWAYS"
    call_exits = Column(Boolean)
    put_exits = Column(Boolean)
    call_itm = Column(Boolean)
    put_itm = Column(Boolean)

    # OI Boundaries
    max_call_oi_strike = Column(Float)
    max_put_oi_strike = Column(Float)
    max_call_oi = Column(BigInteger)
    max_put_oi = Column(BigInteger)
    second_max_call_oi_strike = Column(Float)
    second_max_put_oi_strike = Column(Float)

    # Max pain
    max_pain_strike = Column(Float)

    underlying_price = Column(Float)


# ═══════════════════════════════════════════════════════════
#  MARKET DATA TICK — High-frequency price snapshots
# ═══════════════════════════════════════════════════════════

class MarketTick(Base):
    __tablename__ = "market_ticks"

    id = Column(BigInteger, primary_key=True, autoincrement=True)
    captured_at = Column(DateTime, default=datetime.utcnow, index=True)

    symbol = Column(String(50), nullable=False, index=True)
    ltp = Column(Float, nullable=False)
    open_price = Column(Float)
    high = Column(Float)
    low = Column(Float)
    close = Column(Float)
    volume = Column(BigInteger)
    oi = Column(BigInteger)

    __table_args__ = (
        Index("ix_ticks_symbol_time", "symbol", "captured_at"),
    )


# ═══════════════════════════════════════════════════════════
#  SENTIMENT LOG — Every sentiment reading
# ═══════════════════════════════════════════════════════════

class SentimentLog(Base):
    __tablename__ = "sentiment_logs"

    id = Column(Integer, primary_key=True, autoincrement=True)
    captured_at = Column(DateTime, default=datetime.utcnow, index=True)

    source = Column(String(30), nullable=False)   # "RSS", "REDDIT", "TWITTER"
    source_detail = Column(String(200))            # URL or subreddit name
    title = Column(Text)
    content = Column(Text)
    raw_score = Column(Float)
    compound_score = Column(Float)
    positive = Column(Float)
    negative = Column(Float)
    neutral = Column(Float)
    label = Column(String(20))  # "BULLISH", "BEARISH", "NEUTRAL"
    symbol_mentioned = Column(String(50))


# ═══════════════════════════════════════════════════════════
#  PORTFOLIO SNAPSHOT — Daily portfolio state
# ═══════════════════════════════════════════════════════════

class PortfolioSnapshot(Base):
    __tablename__ = "portfolio_snapshots"

    id = Column(Integer, primary_key=True, autoincrement=True)
    captured_at = Column(DateTime, default=datetime.utcnow, index=True)

    total_capital = Column(Float, nullable=False)
    available_capital = Column(Float, nullable=False)
    used_margin = Column(Float, default=0)
    unrealized_pnl = Column(Float, default=0)
    realized_pnl = Column(Float, default=0)
    total_pnl = Column(Float, default=0)
    total_pnl_pct = Column(Float, default=0)

    open_positions = Column(Integer, default=0)
    total_trades_today = Column(Integer, default=0)
    winning_trades_today = Column(Integer, default=0)
    losing_trades_today = Column(Integer, default=0)

    max_drawdown = Column(Float, default=0)
    sharpe_ratio = Column(Float)
    win_rate = Column(Float)

    portfolio_delta = Column(Float, default=0)
    portfolio_gamma = Column(Float, default=0)
    portfolio_theta = Column(Float, default=0)
    portfolio_vega = Column(Float, default=0)


# ═══════════════════════════════════════════════════════════
#  BACKTEST RESULT — Historical backtest runs
# ═══════════════════════════════════════════════════════════

class BacktestResult(Base):
    __tablename__ = "backtest_results"

    id = Column(Integer, primary_key=True, autoincrement=True)
    created_at = Column(DateTime, default=datetime.utcnow)

    strategy = Column(String(50), nullable=False)
    symbol = Column(String(50), nullable=False)
    start_date = Column(String(20))
    end_date = Column(String(20))
    timeframe = Column(String(10))

    initial_capital = Column(Float)
    final_capital = Column(Float)
    total_pnl = Column(Float)
    total_pnl_pct = Column(Float)
    total_trades = Column(Integer)
    winning_trades = Column(Integer)
    losing_trades = Column(Integer)
    win_rate = Column(Float)
    profit_factor = Column(Float)
    max_drawdown = Column(Float)
    max_drawdown_pct = Column(Float)
    sharpe_ratio = Column(Float)
    calmar_ratio = Column(Float)
    avg_win = Column(Float)
    avg_loss = Column(Float)
    largest_win = Column(Float)
    largest_loss = Column(Float)

    equity_curve = Column(JSON)
    trades_detail = Column(JSON)
    monthly_returns = Column(JSON)
    params = Column(JSON)
